[package]
org = "chathura"
name = "ballerina_edifact"
version = "0.1.0"
distribution = "2201.6.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org="ballerinax"
name="edifact.finance.d96a"
version="0.1.4"
repository="local"
